// examples/react/WorkflowBuilder.jsx
// React wrapper for @one-million-lines/workflow-builder.
//
// The package is framework-agnostic, so React integration is a thin wrapper
// around the framework-neutral factory. React/ReactDOM are NOT dependencies of
// the package — this file lives in the consuming app.
import { useEffect, useRef } from "react";
import { createWorkflowBuilder } from "@one-million-lines/workflow-builder";
import "@one-million-lines/workflow-builder/styles.css";

export function WorkflowBuilder({ initialValue, extensions, dataProvider, onChange }) {
  const hostRef = useRef(null);
  const instanceRef = useRef(null);

  useEffect(() => {
    const builder = createWorkflowBuilder({
      target: hostRef.current,
      initialValue,
      extensions,
      dataProvider,
      onChange,
    });
    instanceRef.current = builder;
    return () => builder.destroy();
    // Mount once; updates flow through the onChange callback / imperative ref.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return <div ref={hostRef} style={{ width: "100%", height: "100%", minHeight: 500 }} />;
}

// Usage:
//
// function App() {
//   return (
//     <WorkflowBuilder
//       initialValue={{ trigger: { type: null, config: {} }, steps: [] }}
//       onChange={(wf) => console.log(wf)}
//     />
//   );
// }

// examples/vue/WorkflowBuilder.vue
<!--
  Vue 3 wrapper for @one-million-lines/workflow-builder.
  The package is framework-agnostic; this SFC wraps the neutral factory.
-->
<template>
  <div ref="host" class="wfb-host" />
</template>

<script setup>
import { onMounted, onBeforeUnmount, ref } from "vue";
import { createWorkflowBuilder } from "@one-million-lines/workflow-builder";
import "@one-million-lines/workflow-builder/styles.css";

const props = defineProps({
  initialValue: { type: Object, default: null },
  extensions: { type: Array, default: () => [] },
});
const emit = defineEmits(["change"]);

const host = ref(null);
let builder = null;

onMounted(() => {
  builder = createWorkflowBuilder({
    target: host.value,
    initialValue: props.initialValue,
    extensions: props.extensions,
    onChange: (wf) => emit("change", wf),
  });
});

onBeforeUnmount(() => builder?.destroy());

defineExpose({
  getValue: () => builder?.getValue(),
  setValue: (v) => builder?.setValue(v),
  validate: () => builder?.validate(),
});
</script>

<style scoped>
.wfb-host {
  width: 100%;
  height: 100%;
  min-height: 500px;
}
</style>

<!--
  Usage:
  <WorkflowBuilder :initial-value="workflow" @change="onChange" />
-->
